# -*- coding: utf-8 -*-
"""cancer or not using svm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JgrRdFY45a4KQ4jWh9pXJdI3HKI0orWW
"""

import sklearn
from sklearn import datasets
from sklearn import svm
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier

cancer=datasets.load_breast_cancer()

#print names of attributes
print(cancer.feature_names)
print(cancer.target_names)

x=cancer.data
y=cancer.target

x_train,x_test,y_train,y_test=sklearn.model_selection.train_test_split(x,y,test_size=0.2)

print(x_train,y_train)

classes= ['malignant' 'benign']

"""#SVM"""

clf=svm.SVC(kernel="linear",C=1)#SUPPORT VECTOR CLASSIFIER
#here, we use kernal as a function to convert 2D to higher dimensional space when the points are not linearly separable
#also, here we increase the accuracy by adding linear kernel
#c corresponds to margin , hardmargin OR softmargin
clf.fit(x_train,y_train)

y_pred=clf.predict(x_test)

acc=metrics.accuracy_score(y_test,y_pred)
print(acc)

"""#KNN"""

clf=KNeighborsClassifier(n_neighbors=9)

clf.fit(x_train,y_train)

y_pred=clf.predict(x_test)

acc=metrics.accuracy_score(y_test,y_pred)
print(acc)